# Generated by Django 5.0.7 on 2024-07-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winestyle',
            old_name='categorization',
            new_name='style',
        ),
    ]
