# Generated by Django 5.0.7 on 2024-07-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0002_rename_categorization_winestyle_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winestyle',
            old_name='style',
            new_name='categorization',
        ),
    ]
